import { chat } from './llm';
import { MODELS, activeCoder, coderLabel } from '../config/models';
import { COMPANY } from '../config/constants';

/**
 * THE CODER - the harness's code-writing arm.
 *
 * When the harness builds a new agent, it also has a dedicated CODER model write a real
 * TypeScript module for that agent (not just the data persona). Kimi K2 (Moonshot) is the
 * default coder; Claude/GPT code as a fallback; with no key the harness emits a real
 * template module. The output is a reviewable ARTIFACT: a human reads the diff and merges
 * it through the normal dev pipeline. Nothing here is hot-loaded into the running app - the
 * OS proposes code, a person ships it, exactly like every other gate in this system.
 */

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'agent';
}

/** The contract every generated agent module implements (kept identical across coder + template). */
const CONTRACT = `// Generated by the harness coder. Review the diff before merging; nothing here runs until a
// human merges it through the dev pipeline.
//
// Target contract (do not change the shapes):
//   export interface AgentInput   { text: string; data?: Record<string, unknown> }
//   export interface AgentContext { remember(s:string,p:string,o:string):Promise<void>;
//                                   recall(q:string):Promise<string[]>;
//                                   company: { name:string; industry:string } }
//   export interface AgentResult  { text: string; actions?: string[] }
//   export const meta = { key, name, pillar, capability }
//   export async function handle(input: AgentInput, ctx: AgentContext): Promise<AgentResult>`;

interface Spec {
  key: string;
  name: string;
  role: string;
  system_prompt: string;
  knowledge: string[];
}

/** The keyless, deterministic module - a real, compilable stub a human can flesh out or merge. */
function templateModule(spec: Spec, finding: any, pillar: string): string {
  const key = slug(spec.name);
  const skills = (spec.knowledge || []).map((k) => `  //  - ${k.replace(/\n/g, ' ')}`).join('\n');
  return `${CONTRACT}

export interface AgentInput { text: string; data?: Record<string, unknown> }
export interface AgentContext {
  remember(subject: string, predicate: string, object: string): Promise<void>;
  recall(query: string): Promise<string[]>;
  company: { name: string; industry: string };
}
export interface AgentResult { text: string; actions?: string[] }

export const meta = {
  key: ${JSON.stringify(key)},
  name: ${JSON.stringify(spec.name)},
  pillar: ${JSON.stringify(finding.pillar_key || pillar)},
  capability: ${JSON.stringify(finding.capability_id || null)},
};

// ${spec.name}: ${spec.role}
// Starting skills:
${skills || '  //  (none yet)'}
export async function handle(input: AgentInput, ctx: AgentContext): Promise<AgentResult> {
  // Ground the response in what the shared brain already knows.
  const known = await ctx.recall(input.text);
  const note = known.length ? \` Context I already hold: \${known.slice(0, 3).join('; ')}.\` : '';

  // TODO(coder): implement the real work for "${finding.title.replace(/"/g, "'")}".
  // For now this records the request and returns a grounded acknowledgement.
  await ctx.remember(meta.name, 'handled', input.text.slice(0, 120));

  return {
    text: \`\${meta.name} for \${ctx.company.name}: on it.\${note}\`,
    actions: ['logged-to-shared-brain'],
  };
}
`;
}

/** Route a coder prompt to Kimi (Moonshot, OpenAI-compatible) / Claude / GPT. */
async function coderChat(system: string, user: string, maxTokens = 1400): Promise<string | null> {
  const coder = activeCoder();
  if (coder === 'kimi') {
    try {
      const res = await fetch(`${MODELS.moonshot.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          authorization: `Bearer ${process.env.MOONSHOT_API_KEY}`,
        },
        body: JSON.stringify({
          model: MODELS.moonshot.chat,
          max_tokens: maxTokens,
          temperature: 0.2,
          messages: [
            { role: 'system', content: system },
            { role: 'user', content: user },
          ],
        }),
      });
      if (!res.ok) throw new Error(`moonshot ${res.status}: ${await res.text()}`);
      const data = (await res.json()) as any;
      return (data.choices?.[0]?.message?.content || '').trim() || null;
    } catch (err) {
      console.warn('[coder] kimi failed, degrading:', (err as Error).message);
      return null;
    }
  }
  if (coder === 'anthropic' || coder === 'openai') {
    const res = await chat(
      [
        { role: 'system', content: system },
        { role: 'user', content: user },
      ],
      { maxTokens }
    );
    return res?.text || null;
  }
  return null; // keyless
}

function stripFences(s: string): string {
  return s
    .replace(/^```(?:ts|typescript|javascript|js)?\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();
}

/**
 * Write the agent's code module. Returns the code, where it would live, and which coder
 * wrote it. Keyless (or on any coder failure) returns a real template module, so the harness
 * always produces a mergeable artifact.
 */
export async function generateAgentModule(
  spec: Spec,
  finding: any,
  pillar: string
): Promise<{ code: string; path: string; engine: string }> {
  const key = slug(spec.name);
  const path = `server/src/agents/generated/${key}.ts`;
  const template = templateModule(spec, finding, pillar);

  if (activeCoder() === 'none') return { code: template, path, engine: 'template' };

  const system = `You are the CODER inside ${COMPANY.name}'s AI operating system. Write ONE self-contained TypeScript module for a new agent. Output ONLY the code, no prose, no markdown fences. It must implement this contract exactly:\n${CONTRACT}\nKeep it dependency-free (no imports), fully typed, and realistic for a ${COMPANY.industry} company. Put real, useful logic in handle(); use ctx.recall / ctx.remember; leave a TODO only where a real external integration would be needed.`;
  const user = `AGENT: ${spec.name}\nROLE: ${spec.role}\nPILLAR: ${finding.pillar_key || pillar}\nWHY IT EXISTS (the gap): ${finding.title}\nDETAIL: ${finding.detail || ''}\nSTARTING SKILLS:\n- ${(spec.knowledge || []).join('\n- ')}`;

  const out = await coderChat(system, user);
  if (out) {
    const code = stripFences(out);
    // Basic sanity: it must actually be the module we asked for.
    if (/export\s+async\s+function\s+handle/.test(code) && /export\s+const\s+meta/.test(code)) {
      return { code, path, engine: `coder-${activeCoder()}` };
    }
  }
  return { code: template, path, engine: 'template' };
}

export { coderLabel };
